In [26]:
import numpy as np

L=0.1
epochs = 1
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,0])

iLS,hLS,oLS = 2,3,1

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_(x):
    return x*(x-1)

hidden_weight = np.random.uniform(size=(iLS,hLS))
print("Hidden Weights")
print(hidden_weight)
output_weight = np.random.uniform(size=(hLS,oLS))
print("output weights")
print(output_weight)

for i in range(epochs):
    hidden_res = sigmoid(np.dot(x,hidden_weight))
    print("Hidden Result")
    print(hidden_res)
    
    
    output = np.dot(h_res,output_weight)
    print("Output")
    print(output)
    
    
    Error = y - output
    print("Error")
    print(Error)
    
    cError = Error * L
    print("Change in error")
    print(cEr)
    
    cOutputWeight = output_weight + hidden_res.T.dot(cError)
    print("Change in output weight")
    print(cOutputWweight)
    
    cHiddenRes = cEr.dot(cOutputWeight.T) * sigmoid_(hidden_res)
    print("Change in Hidden Result ")
    print(cHiddenRes)
    
    cHiddenWeight= hidden_weight + x.T.dot(cHiddenRes)
    print("Change in hidden weight ")
    print(cHiddenWeight)
    

print("Output")
print(output)

Hidden Weights
[[8.39169146e-01 4.03997542e-04 5.22270350e-01]
 [5.36589489e-01 3.00159017e-01 4.26736882e-01]]
output weights
[[0.58039676]
 [0.89578895]
 [0.04930348]]
Hidden Result
[[0.5        0.5        0.5       ]
 [0.63101869 0.57448139 0.6050942 ]
 [0.6982902  0.500101   0.6276785 ]
 [0.79830895 0.57458014 0.72091548]]
Output
[[0.76274459]
 [0.83009689]
 [0.9421163 ]
 [0.99786183]]
Error
[[-0.76274459  0.23725541  0.23725541 -0.76274459]
 [-0.83009689  0.16990311  0.16990311 -0.83009689]
 [-0.9421163   0.0578837   0.0578837  -0.9421163 ]
 [-0.99786183  0.00213817  0.00213817 -0.99786183]]
Change in error
[[-0.04932009  0.05067991  0.05067991 -0.04932009]
 [-0.05250312  0.04749688  0.04749688 -0.05250312]
 [-0.05849928  0.04150072  0.04150072 -0.05849928]
 [-0.06111506  0.03888494  0.03888494 -0.06111506]]
Change in output weight
[[0.14178639 0.35966052 0.35966052 0.14178639]
 [0.36784659 0.62221088 0.62221088 0.36784659]
 [0.02393483 0.27240087 0.27240087 0.02393483]]
Change in