In [11]:
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [12]:
iris = datasets.load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target)

In [13]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
print(metrics.accuracy_score(y_test,model.predict(x_test)))
print(model.score(x_test,y_test))

0.9736842105263158
0.9736842105263158


In [18]:
for i in range(len(x_test)):
    ni = np.array([x_test[i]])
    print(ni)
    actual = y_test[i]
    pred = model.predict(ni)
    act_l = iris["target_names"][actual]
    pred_l= iris["target_names"][pred]
    print(actual,act_l,pred,pred_l)

[[6.1 3.  4.6 1.4]]
1 versicolor [1] ['versicolor']
[[6.1 3.  4.9 1.8]]
2 virginica [2] ['virginica']
[[6.4 2.7 5.3 1.9]]
2 virginica [2] ['virginica']
[[5.1 3.5 1.4 0.3]]
0 setosa [0] ['setosa']
[[6.8 3.  5.5 2.1]]
2 virginica [2] ['virginica']
[[6.2 2.9 4.3 1.3]]
1 versicolor [1] ['versicolor']
[[6.  2.2 4.  1. ]]
1 versicolor [1] ['versicolor']
[[6.7 3.1 4.7 1.5]]
1 versicolor [1] ['versicolor']
[[5.  3.4 1.5 0.2]]
0 setosa [0] ['setosa']
[[5.6 3.  4.1 1.3]]
1 versicolor [1] ['versicolor']
[[6.4 2.8 5.6 2.2]]
2 virginica [2] ['virginica']
[[7.9 3.8 6.4 2. ]]
2 virginica [2] ['virginica']
[[6.  3.  4.8 1.8]]
2 virginica [2] ['virginica']
[[7.2 3.  5.8 1.6]]
2 virginica [2] ['virginica']
[[7.1 3.  5.9 2.1]]
2 virginica [2] ['virginica']
[[5.7 2.8 4.1 1.3]]
1 versicolor [1] ['versicolor']
[[5.  3.5 1.6 0.6]]
0 setosa [0] ['setosa']
[[5.5 2.3 4.  1.3]]
1 versicolor [1] ['versicolor']
[[5.  3.6 1.4 0.2]]
0 setosa [0] ['setosa']
[[4.4 3.2 1.3 0.2]]
0 setosa [0] ['setosa']
[[6.3 2.7 4.9 1.